Adding forwarded address support
opensciencegrid/gracc-collector pull request #18
Opened 2017-04-26 19:04 UTC by djw8605

Log the correct remote address by looking at the X-Real-IP or
X-Forwarded-For headers.  If they exist, then use those for the remote
address.  Otherwise use the normal RemoteAddr from the Header.

Fixes #17

2017-04-26 19:15 UTC, retzkek requested changes
`Header` is a `map[string][]string` so directly accessing it will return a slice of strings. Probably better to use the `Header.Get()` method (https://golang.org/pkg/net/http/#Header.Get) to get the first value. I'm not 100% sure we want the first value (`X-Forwarded-For` can list multiple forwards), but what else would we want in that case?

2017-04-26 19:18 UTC, djw8605 commented
So something like:
```go
if remote, ok := r.Header["X-Real-IP"]; ok {
  remoteAddr = r.Header.Get("X-Real-IP")
} else if { ...
```

2017-04-26 19:20 UTC, retzkek commented
I'd do:

```go
if remote := r.Header.Get("X-Real-IP"); remote != "" {
  remoteAddr = remote
} else if { ...
```

2017-04-26 19:28 UTC, djw8605 commented
Well, I'm not sure that was any easier than you making the change, but at least I learned a bit more go.

2017-04-27 17:33 UTC, retzkek approved these changes

2017-04-27 17:40 UTC, merged